{
 "title": "Derova - Community Dashboard v2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "algod_ledger_round", "legendFormat": "__auto" },
    { "expr": "algod_ledger_dbround", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Load",
   "type": "timeseries",
   "description": "1/5/15 minute average of the node load",
   "gridPos": { "h": 4, "w": 10, "x": 9, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peering",
   "type": "bargauge",
   "description": "Peers are the other nodes your node is directly connected to",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "algod_network_peers", "legendFormat": "__auto" },
    { "expr": "algod_network_outgoing_peers", "legendFormat": "__auto" },
    {
     "expr": "algod_network_outgoing_connections",
     "legendFormat": "__auto"
    },
    { "expr": "algod_network_incoming_peers", "legendFormat": "__auto" },
    {
     "expr": "algod_network_incoming_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(algorand_algorand_telemetry_events_total{msg_type=\"/Agreement/BlockAccepted\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(algorand_algorand_telemetry_events_total{msg_type=\"/Agreement/BlockProposed\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(algorand_algorand_telemetry_events_total{msg_type=\"/Agreement/VoteSent\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(algorand_algorand_telemetry_events_total{msg_type=\"/ApplicationState/Heartbeat\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "description": "Total and per core CPU utilisation",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (avg by (cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "description": "Memory usage with 80% (Yellow), 90% (Orange) and 100% (Red) indicators",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Algod Uptime",
   "type": "stat",
   "description": "Algod process (not system) uptime",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time",
   "type": "stat",
   "description": "Reporting if clock is synchronized to a reliable server",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_timex_sync_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ledger TPS",
   "type": "stat",
   "description": "Algod ledger transactions (Total)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_ledger_transactions_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX Pool Count",
   "type": "stat",
   "description": "Number of messages in the pool",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "algod_tx_pool_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Load (1m avg)",
   "type": "stat",
   "description": "1 minute average of the node load",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Algod Build Information",
   "type": "table",
   "description": "Build information of the Algod service",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 9 },
   "targets": [
    { "expr": "algod_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Utilisation",
   "type": "timeseries",
   "description": "Total bytes being read from and written to the disk",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem and IO",
   "type": "timeseries",
   "description": "Disk Size, Disk Consumed, and Disk IO ",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 10 },
   "targets": [
    { "expr": "node_filesystem_size_bytes", "legendFormat": "__auto" },
    {
     "expr": "node_filesystem_size_bytes-node_filesystem_avail_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_network_message_received_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agreements handled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_agreement_handled[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Votes handled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_agreement_handled_vote[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_network_message_sent_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agreements dropped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_agreement_dropped[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Votes dropped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_agreement_dropped_vote[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "options": {
    "content": "<img src=\"https://algorand.ing/images/dashboard-image.png\"></img>"
   }
  },
  {
   "title": "Proposals handled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_agreement_handled_proposal[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Messages Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_network_p2p_message_received_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bundles handled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_agreement_handled_bundle[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Transfer",
   "type": "timeseries",
   "description": "Network traffic coming into (Ingress) and leaving (egress) the node",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate (algod_network_received_bytes_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate (algod_network_sent_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "stat",
   "description": "Number of network transmit errors as a ratio based on the number of total transmit packets",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_errs_total[1m]) / rate(node_network_transmit_packets_total[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposals dropped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_agreement_dropped_proposal[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Messages Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_network_p2p_message_sent_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bundles dropped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(algod_agreement_dropped_bundle[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}